/* Generated By:JavaCC: Do not edit this line. TiggerConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface TiggerConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int NUMBER = 4;
  /** RegularExpression Id. */
  int DIGIT = 5;
  /** RegularExpression Id. */
  int EOL = 6;
  /** RegularExpression Id. */
  int PRINT = 7;
  /** RegularExpression Id. */
  int LPAR = 8;
  /** RegularExpression Id. */
  int RPAR = 9;
  /** RegularExpression Id. */
  int WORD = 10;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\r\"",
    "\"\\t\"",
    "<NUMBER>",
    "<DIGIT>",
    "\"\\n\"",
    "\"print\"",
    "\"(\"",
    "\")\"",
    "<WORD>",
    "\",\"",
    "\"quit\"",
    "\"help\"",
    "\"+\"",
    "\"-\"",
    "\"<\"",
    "\">\"",
    "\"=\"",
    "\"<=\"",
    "\">=\"",
    "\"<>\"",
    "\"*\"",
    "\"/\"",
    "\"call\"",
    "\"if \"",
    "\" then \"",
    "\" else \"",
    "\"let\"",
    "\"var\"",
    "\":=\"",
    "\"in\"",
    "\"end\"",
    "\"function\"",
  };

}
